/** Prompt construction (BUILD_SPEC section 11). */

import { formatINR, formatVariance } from '../lib/money';
import { EXCEPTION_TYPES } from '../domain/taxonomy';
import type { CandidateGroup, GatewayRecord, LedgerRecord, MatchGroup } from '../domain/types';
import type { EngineState } from '../engine/state';

export const SYSTEM_PROMPT = [
  'You are a reconciliation adjudicator for an Indian merchant finance operation.',
  '',
  'You will be shown one financial record that automated matching could not resolve, and a',
  'numbered list of candidate matches that were generated by deterministic rules. Each',
  'candidate already includes computed amount deltas, date gaps and reference comparisons.',
  '',
  'Your only job is to decide which candidate, if any, is correct.',
  '',
  'Rules you must follow:',
  '- You may only select a candidate from the list provided. You may not propose any other match.',
  '- You may not calculate, adjust, or state any monetary amount. The amounts shown are final.',
  '- If two or more candidates are equally plausible, you must return "insufficient_evidence".',
  '  Do not break a tie by guessing.',
  '- If no candidate is plausible, return "no_match".',
  '- Confidence must reflect genuine uncertainty. A confidence above 0.9 means you would stake',
  '  a payment on it being correct.',
  '- The rationale must name the specific evidence that decided it, in under 240 characters.',
  '',
  'Reply with a single JSON object and nothing else:',
  '{"decision": "...", "candidate_id": "...", "exception_type": "...", "confidence": 0.0,',
  ' "rationale": "...", "evidence_ids": ["..."]}',
].join('\n');

function describeLedger(l: LedgerRecord): string {
  return l.invoice_no + ' (' + l.customer_name + ', ' + formatINR(l.gross_amount_paise) + ', issued ' + l.issue_date + ')';
}

function describeGateway(g: GatewayRecord): string {
  return (
    g.payment_id + ' (' + formatINR(g.amount_paise) + ' gross, ' + formatINR(g.fee_paise) + ' fee, ' +
    formatINR(g.net_paise) + ' net, ' + g.method + ', captured ' + g.captured_at.slice(0, 10) + ')'
  );
}

export interface PromptResult {
  user: string;
  recordIds: string[];
  candidateIds: string[];
}

export function buildUserPrompt(state: EngineState, match: MatchGroup, candidates: CandidateGroup[]): PromptResult {
  const bankId = match.bank_ids[0];
  const bank = bankId ? state.bankById.get(bankId) : undefined;
  const recordIds = new Set<string>();
  const lines: string[] = [];

  lines.push('UNMATCHED RECORD');
  if (bank) {
    recordIds.add(bank.record_id);
    lines.push('  id: ' + bank.record_id);
    lines.push('  source: bank');
    lines.push('  value_date: ' + bank.value_date);
    lines.push('  amount: ' + formatINR(bank.amount_paise));
    lines.push('  narration: ' + bank.narration);
    lines.push('  extracted references: ' + JSON.stringify(bank.extracted_references.slice(0, 6)));
  }
  lines.push('');
  lines.push('CANDIDATES');
  lines.push('');

  candidates.forEach((candidate, i) => {
    lines.push('[' + (i + 1) + '] candidate_id: ' + candidate.candidate_id);
    for (const id of candidate.ledger_ids) {
      const l = state.ledgerById.get(id);
      if (l) {
        recordIds.add(id);
        lines.push('    ledger: ' + describeLedger(l));
      }
    }
    for (const id of candidate.gateway_ids) {
      const g = state.gatewayById.get(id);
      if (g) {
        recordIds.add(id);
        lines.push('    gateway: ' + describeGateway(g));
      }
    }
    lines.push('    computed:');
    lines.push('      amount delta vs bank: ' + formatVariance(candidate.variance_paise));
    lines.push('      date gap: ' + candidate.date_gap_days + ' days');
    lines.push('      reference similarity: ' + candidate.score_components.reference_similarity.toFixed(2));
    lines.push('      customer match: ' + candidate.score_components.customer_match.toFixed(2));
    lines.push('    rules note: ' + candidate.rules_note);
    lines.push('');
  });

  lines.push('EXCEPTION TYPES AVAILABLE');
  lines.push('  ' + EXCEPTION_TYPES.join(', '));

  return {
    user: lines.join('\n'),
    recordIds: [...recordIds],
    candidateIds: candidates.map((c) => c.candidate_id),
  };
}
